<a href="https://colab.research.google.com/github/Ethanqg0/GraphTheoryBenchmarks/blob/master/CSE_20_Testout_Exam_September_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CSE 20 Testout, September 2024

### Question format

For each question, there is:

* A text description of the problem.
* One or more places where you have to insert your solution.  You need to complete every place marked:

    `# YOUR SOLUTION HERE`
    
    and you should not modify any other place.

* One or more test cells.  Each cell is worth some number of points, marked at the top.  You should not modify these tests cells.  The tests pass if no error is printed out: when there is a statement that says, for instance:

    `assert x == 2`
    
    then the test passes if `x` has value 2, and fails (raises an exception) otherwise.

* **Please do not delete, reorder or add cells!** The test is autograded, and if you modify the test by adding or deleting cells, even if you re-add cells you delete, you may not receive credit.

* **Please do not import modules.** You do not need any, and if you import a module, you code will fail in testing.

* **Write your solution only in the solution cell.** Modifications to other cells will be discarded before grading.

* You can write out print statements in your code, to help you test/debug it. But remember: the code is graded on the basis of what it returns, and not on the basis of what it prints.

### Hints

* A statement `assert x == y` will check that `x == y`, and raise an exception if `x` is different from `y`.  We use these statements to test your code.  If they do raise an exception, it means there is something wrong with your code.
* If you work with Colab, occasionally you may get disconnected; this happens especially if you are inactive.  In that case, you need to rerun the notebook from the beginning, as the server has "forgotten" its state.
* Colab keeps a revision history of your work (`[File > Revision history]`), so if something happens, your work should not be lost.


## Question 1: Where can the rook go?

### The board

We will represent a board via a numpy matrix.  Don't worry if you don't know what this is: it's really simple.  If the board is `board`, then:

    board[i, j]

returns:

* 0 if the position i, j in the board is empty,
* 1 if it contains a piece of our color, and
* -1 if it contains an adversary piece.  

If you do:

    board.shape

you get a tuple indicating the shape of the board, for instance, (8, 8).
That's pretty much all you need to know!

### The rook

A rook can move horizontally or vertically, in any direction, but it cannot "jump" over another piece.  The rook can go to places where there is an adversary piece: in that case, it stops there (and eats the piece).

Let's consider this example.  Here is the board status:

    0  0  0  0  0  0
    0  1  0 -1  0  0
    1  0  0 *1* 0 -1
    0  0  0  0  0  0
    0  1  0  1  0  0
    0  1  0  0  0 -1

Assume the rook is at position (2, 3) (2nd row, 3rd column), that is, the rook is the 1 we indicated as `*1*` above (we use `*1*` just to distinguish it from other 1s, but remember, the board just contains a 1 there).

Where can the rook go?  

* If it goes up, it can go to (1, 3) (and eat the adversary piece there).
* If it goes down, it can go to (3, 3) (and can go no further).
* If it goes right, it can go to (2, 4), and to (2, 5) (in the latter case, eating the adversary there).
* If it goes left, it can go to (2, 2), and (2, 1) (and can go no further).

In total, the places where it can go are:

    {(1, 3), (3, 3), (2, 4), (2, 5), (2, 2), (2, 1)}

### The function `rook`

You have to write a function `rook` so that `rook(board, i, j)` returns the set of locations (as above) where the rook can go starting from position i, j.  Of course, you can assume `board[i, j] = 1`, since the rook will be there.  

In [28]:
import numpy as np

In [87]:
def rook(board, i, j):
    assert board[i][j] == 1  # The rook is there.
    locations = set()
    rows, cols = len(board), len(board[0])

    """
      Pseudocode
      Locations will be a set, each location will be a tuple. We will go in all four directions and append the tuple to the locations set.
      We will check each direction by doing a while loop. Each movement we will append the location if appropriate
    """

    # Moving right
    temp_j = j
    while temp_j + 1 < cols:  # Check for right bounds
        temp_j += 1
        location = (i, temp_j)

        if board[i][temp_j] == 0:  # Empty square
            locations.add(location)
        elif board[i][temp_j] == -1:  # Enemy piece
            locations.add(location)
            break
        else:  # Friendly piece or out of bounds
            break

    # Moving left
    temp_j = j
    while temp_j - 1 >= 0:  # Check for left bounds
        temp_j -= 1
        location = (i, temp_j)

        if board[i][temp_j] == 0:
            locations.add(location)
        elif board[i][temp_j] == -1:
            locations.add(location)
            break
        else:
            break

    # Moving up
    temp_i = i
    while temp_i - 1 >= 0:  # Check for upper bounds
        temp_i -= 1
        location = (temp_i, j)

        if board[temp_i][j] == 0:
            locations.add(location)
        elif board[temp_i][j] == -1:
            locations.add(location)
            break
        else:
            break

    # Moving down
    temp_i = i
    while temp_i + 1 < rows:  # Check for lower bounds
        temp_i += 1
        location = (temp_i, j)

        if board[temp_i][j] == 0:
            locations.add(location)
        elif board[temp_i][j] == -1:
            locations.add(location)
            break
        else:
            break

    return locations


To make testing easier, here is a function that displays with "2" the places where the rook can go.

In [88]:
def display_solution(board, places):
    board = board.copy()
    for i, j in places:
        board[i, j] = 2
    print(board)

In [89]:
# Tests 5 points: on an otherwise empty board.

import numpy as np

board = np.zeros((4, 4))
board[1, 2] = 1
places = rook(board, 1, 2)
display_solution(board, places)
print(rook(board, 1, 2))
assert rook(board, 1, 2) == {(1, 1), (0, 2), (2, 2), (1, 0), (3, 2), (1, 3)}


[[0. 0. 2. 0.]
 [2. 2. 1. 2.]
 [0. 0. 2. 0.]
 [0. 0. 2. 0.]]
{(1, 1), (0, 2), (2, 2), (1, 0), (3, 2), (1, 3)}


In [90]:
# Tests 10 points: on a board with some of our pieces, but no adversary piece.

board = np.zeros((4, 4))
board[1, 2] = 1
board[2, 2] = 1
places = rook(board, 1, 2)
display_solution(board, places)
print( rook(board, 1, 2) )
assert rook(board, 1, 2) == {(1, 1), (0, 2), (1, 0), (1, 3)}


[[0. 0. 2. 0.]
 [2. 2. 1. 2.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
{(1, 0), (1, 1), (1, 3), (0, 2)}


In [91]:
# Tests 10 points: on a board with both our and adversary pieces.

board = np.zeros((6, 8))
board[3, 2] = 1
board[2, 2] = -1
board[3, 0] = 1
board[3, 4] = -1
places = rook(board, 3, 2)
display_solution(board, places)
assert rook(board, 3, 2) == {(3, 4), (3, 1), (4, 2), (3, 3), (2, 2), (5, 2)}


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0.]
 [1. 2. 1. 2. 2. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0.]]


## Question 2: Count the function calls

Write a function `f`, which returns the number of times it has been called since its last call with argument 0.
So if you call

    f(0)

it returns 0, and if you call then:

    f(1)    return  1
    f(4)    returns 2
    f(0)    returns 0 (the count is reset)
    f(-4)   returns 1
    f(5)    returns 2
    f(4)    returns 3

and so on.  The function should be able to handle any argument.  All that matters, really, is whether the argument is 0 or not.

In [92]:
# You can write here any setup code that you might find useful.
## BEGIN SOLUTION
class Counter(object):
    counter = 0 # changed variable to static so that the value persists between function calls

    def increment():
      counter += 1

my_counter = Counter()
## END SOLUTION

# Here is your function declaration.
def f(n):
    if n == 0:
      my_counter.counter = 0
      return my_counter.counter
    else:
      my_counter.counter += 1
      return my_counter.counter

In [93]:
# Tests 15 points: Let's test the function.

assert f(0) == 0
assert f(1) == 1
assert f(2) == 2
assert f(0) == 0
assert f(-3) == 1
assert f("cat") == 2
assert f(None) == 3


## Question 3: 3D boxes

You must fill in the definition of a `Box` class.  You create a box by specifying its width, length, and height:

    b = Box(3, 4, 5)
    
The box must have three methods:

    b.volume()
    
must return the volume of the box.
If you have two boxes, b1 and b2, then

    b1.is_bigger_than(b2)
    
must return `True` if `b1` has volume that is bigger (>) than `b2`, and `False` otherwise.

Finally,

    b1.can_contain(b2)

must return `True` if `b1` can contain `b2`, that is, if you can put box `b2` inside box `b1`, perhaps rotating it to orient it in the best way, but keeping the sides parallel to the sides of the boxes.  In practice, `b1.can_contain(b2)` holds if you can associate the dimensions of `b1` to the dimensions of `b2` in such a way that the dimensions of `b1` are all bigger than the dimensions of `b2`.  


In [121]:
class Box(object):
    """A class representing a box.
    You create a Box of size 3 x 4 x 5 by calling Box(3, 4, 5).
    The box must have two methods:
    volume() returns the volume,
    is_bigger_than(b) returns whether the volume of this box is bigger than
    that of box b.
    can_contain(b) if you can put box b inside this box, keeping the faces of the boxes parallel.
    """

    def __init__(self, width, length, height):
      self.width = width
      self.length = length
      self.height = height


    def volume(self):
      return self.width * self.length * self.height

    def is_bigger_than(self, object):
      if self.volume() > object.volume():
        return True
      else:
        return False

    def can_contain(self, object):

      if self.width >= object.width and self.height >= object.height and self.length >= object.length:
        return True
      elif self.width >= object.height and self.height >= object.length and self.length >= object.width:
        return True
      elif self.width >= object.length and self.height >= object.width and self.length >= object.height:
        return True
      else:
        return False



In [110]:
# Tests 5 points: volume.

def check_equal(x, y):
    if x != y:
        print("Error:")
        print("    Your answer was:", x)
        print("    Correct answer: ", y)
    assert x == y

check_equal(Box(3, 4, 5).volume(), 60)
check_equal(Box(5, 5, 5).volume(), 125)
b = Box(1, 2, 3)
check_equal(b.volume(), 6)


In [111]:
# Tests 5 points: is_bigger_than.

check_equal(Box(3, 4, 5).is_bigger_than(Box(2, 3, 4)), True)
check_equal(Box(2, 3, 4).is_bigger_than(Box(5, 6, 7)), False)


In [112]:
# Tests 5 points: can_contain, simple cases.

check_equal(Box(3, 4, 5).can_contain(Box(2, 3, 4)), True)
check_equal(Box(2, 3, 4).can_contain(Box(5, 6, 7)), False)


In [122]:
# Tests 10 points: can_contain, more complex cases.

# These cases need the inner box to be rotated.

check_equal(Box(3, 4, 5).can_contain(Box(5, 3, 4)), True)
check_equal(Box(6, 6, 2).can_contain(Box(2, 3, 6)), True)
check_equal(Box(6, 6, 2).can_contain(Box(2, 7, 6)), False)
check_equal(Box(6, 6, 2).can_contain(Box(2, 6, 5)), True)
